### ISSUE TITLE
ENH: have act.discovery.get_armfiles.download_data return a list of files

### ISSUE THREAD

**Issue by scollis** [ARM-DOE/ACT#292] opened 2021-03-04 22:21 UTC
As it says, to allow automation have act.discovery.get_armfiles.download_data return the filenames of files downloaded.

**Comment by AdamTheisen** [comment] 2021-03-05 16:26
Thanks @scollis we will take a look.  @jhemedin would you want to take a look and see if it's a simple update?  The code is from getFiles.py on https://adc.arm.gov/armlive/

**Comment by jhemedin** [comment] 2021-03-05 16:35
Yeah I can take a look at it.

**Comment by jhemedin** [comment] 2021-03-09 15:41
act.discovery.get_armfiles.download already returns filenames as the files are being downloaded. Or is the issue wanting to know the file names before downloading?

**Comment by scollis** [comment] 2021-03-09 15:43
Hmmm I had it returning None.. I might be using an old version

**Comment by AdamTheisen** [comment] 2021-03-09 16:11
@jhemedin @scollis I believe the issue is that we do print out the file names to the screen when downloading, but we don't return a list of the files that were downloaded.  I think we would want to add a return statement to download_data that returns the filename (fname) with possible the write path (output_dir).

**Comment by scollis** [comment] 2021-03-09 17:46
Yes.. if you can have the function return the file names that would be great

**Comment by AdamTheisen** [comment] 2021-03-30 14:48
@jhemedin With the ARM API being down it brought to light some issues with testing/bugs in the code.  I put in some fixes but also just added in a fix for this issue.  Will want you to review #304 when you get a chance.  Thanks!

**Comment by AdamTheisen** [comment] 2021-04-01 14:18
@scollis this should be implemented now with #304

**Closed by AdamTheisen** 2021-04-01 14:18 UTC
Labels: enhancement
